# Part 3: release history in PostGIS

FHFA re-estimates its whole history in every release, so an analyst needs to know **what the numbers were in each release**. We keep every release in the database, keyed by its **publication date** (the "Last updated" line).

| Object | Returns |
|---|---|
| `hpi_as_of(d date)` | `fips, year, hpi`: FHFA county values as published, from the newest release published on or before `d` |
| `layer_as_of(d date)` | `geoid, status, hpi_yoy_pct, hpi_cagr_5y_pct, …`: our layer as built from that release |
| `hpi_revisions` | `fips, year, old_hpi, new_hpi, …` between the two most recent releases |
| `status_changes` | `geoid, old_status, new_status, …` between the two most recent releases |

**Rule:** `python -m src.part3 <release>` run twice for the same release changes nothing.

Before running: Docker Desktop is open and `docker compose up -d` reports `(healthy)`.

In [1]:
import io
import os
import sys
from pathlib import Path

import pandas as pd
import psycopg2
import shapely

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))
from src import part1, part2

pd.set_option("display.width", 200)
DATA_DIR = ROOT / "data"
RELEASES = [DATA_DIR / "fhfa", DATA_DIR / "fhfa" / "next_release"]
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://takehome:takehome@localhost:5432/takehome")


def q(sql, params=None):
    """Run a query and return a DataFrame."""
    with conn.cursor() as cur:
        cur.execute(sql, params)
        rows = cur.fetchall()
        cols = [c.name for c in cur.description]
    conn.rollback()  # read-only; don't leave a transaction open
    return pd.DataFrame(rows, columns=cols)

## Step 1: Connect

`RESET = True` drops everything Part 3 creates, so the notebook shows a load into an **empty** database (like the reviewers' fresh container) followed by a repeat load. Set it to `False` to keep what is already loaded.

In [2]:
RESET = True

conn = psycopg2.connect(DATABASE_URL)
if RESET:
    with conn, conn.cursor() as cur:
        cur.execute("""
            DROP VIEW IF EXISTS status_changes, hpi_revisions, latest_two_releases;
            DROP FUNCTION IF EXISTS layer_as_of(date), hpi_as_of(date), release_as_of(date);
            DROP TABLE IF EXISTS layer_values, fhfa_county_hpi, county_geom, releases;
        """)
q("SELECT version() AS postgres, postgis_lib_version() AS postgis")

                                            postgres postgis
0  PostgreSQL 17.5 (Debian 17.5-1.pgdg110+1) on x...   3.5.2

## Step 2: Tables

```
releases          one row per FHFA release         PK release_date
fhfa_county_hpi   FHFA county values as published   PK (release_date, fips, year)
county_geom       county shapes, stored once        PK geoid
layer_values      our layer per release             PK (release_date, geoid)
```

- **`fhfa_county_hpi` keeps every row of the file, including blanks** (`hpi` null), because a blank *is* what FHFA published. Codes are stored as FHFA wrote them, so the old release keeps CT's 8 old counties.
- **Shapes are stored once.** Both releases use the same 2024 boundaries, so per-release copies would just duplicate 16 MB of geometry.
- **No `loaded_at` column.** A load timestamp would change on every run and break "running twice changes nothing".

In [3]:
SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS releases (
    release_date date PRIMARY KEY,          -- FHFA 'Last updated' date
    latest_year  integer NOT NULL           -- L used for the layer metrics
);

CREATE TABLE IF NOT EXISTS fhfa_county_hpi (
    release_date date    NOT NULL REFERENCES releases ON DELETE CASCADE,
    fips         text    NOT NULL,
    year         integer NOT NULL,
    hpi          double precision,          -- null where FHFA left it blank
    PRIMARY KEY (release_date, fips, year)
);

CREATE TABLE IF NOT EXISTS county_geom (
    geoid text PRIMARY KEY,
    name  text NOT NULL,
    state text NOT NULL,
    geom  geometry(MultiPolygon, 4326) NOT NULL
);
CREATE INDEX IF NOT EXISTS county_geom_gix ON county_geom USING gist (geom);

CREATE TABLE IF NOT EXISTS layer_values (
    release_date    date NOT NULL REFERENCES releases ON DELETE CASCADE,
    geoid           text NOT NULL REFERENCES county_geom,
    hpi_yoy_pct     double precision,
    hpi_cagr_5y_pct double precision,
    status          text NOT NULL,
    yoy_source      text,
    cagr_source     text,
    coverage        double precision,
    PRIMARY KEY (release_date, geoid)
);
"""

with conn, conn.cursor() as cur:
    cur.execute(SCHEMA_SQL)
q("""SELECT table_name FROM information_schema.tables
     WHERE table_schema = 'public' AND table_name <> 'spatial_ref_sys' ORDER BY 1""")

          table_name
0        county_geom
1    fhfa_county_hpi
2  geography_columns
3   geometry_columns
4       layer_values
5           releases

## Step 3: The as-of functions

Both pick **the newest release published on or before `d`**. Before the first release they return no rows.

In [4]:
FUNCTIONS_SQL = """
CREATE OR REPLACE FUNCTION release_as_of(d date) RETURNS date
LANGUAGE sql STABLE AS $$
    SELECT max(release_date) FROM releases WHERE release_date <= d
$$;

CREATE OR REPLACE FUNCTION hpi_as_of(d date)
RETURNS TABLE (fips text, year integer, hpi double precision)
LANGUAGE sql STABLE AS $$
    SELECT h.fips, h.year, h.hpi
    FROM fhfa_county_hpi h
    WHERE h.release_date = release_as_of(d)
$$;

CREATE OR REPLACE FUNCTION layer_as_of(d date)
RETURNS TABLE (geoid text, name text, state text, status text,
               hpi_yoy_pct double precision, hpi_cagr_5y_pct double precision,
               yoy_source text, cagr_source text, coverage double precision,
               release_date date, latest_year integer, geom geometry)
LANGUAGE sql STABLE AS $$
    SELECT v.geoid, g.name, g.state, v.status,
           v.hpi_yoy_pct, v.hpi_cagr_5y_pct, v.yoy_source, v.cagr_source, v.coverage,
           v.release_date, r.latest_year, g.geom
    FROM layer_values v
    JOIN county_geom g USING (geoid)
    JOIN releases r USING (release_date)
    WHERE v.release_date = release_as_of(d)
$$;
"""

with conn, conn.cursor() as cur:
    cur.execute(FUNCTIONS_SQL)
q("SELECT proname FROM pg_proc WHERE proname IN ('release_as_of', 'hpi_as_of', 'layer_as_of') ORDER BY 1")

         proname
0      hpi_as_of
1    layer_as_of
2  release_as_of

## Step 4: An idempotent loader

Each table is loaded the same way, inside **one transaction per release**:

1. `COPY` the new rows into a temporary staging table (fast, and nothing is touched yet).
2. `DELETE` rows of this release that are no longer in the staging table.
3. `INSERT … ON CONFLICT DO UPDATE … WHERE (old values) IS DISTINCT FROM (new values)`: new rows are inserted, changed rows updated, and **identical rows are left alone**.

On a second run of the same release, steps 2–3 touch **zero rows**, so "running twice changes nothing" holds literally, not just "ends up looking the same". The counts returned below prove it.

If anything fails, the transaction rolls back and the database keeps the previous state.

In [5]:
def sync_table(cur, table: str, df: pd.DataFrame, keys: list[str], scope_sql: str = "TRUE",
               scope_params: tuple = ()) -> dict:
    """Make the rows of `table` within `scope_sql` equal to `df`, touching only rows that differ."""
    cols = list(df.columns)
    values = [c for c in cols if c not in keys]
    stage = f"stage_{table}"
    cur.execute(f"CREATE TEMP TABLE {stage} (LIKE {table}) ON COMMIT DROP")
    buf = io.StringIO()
    df.to_csv(buf, index=False, header=False)   # floats are written in full (round-trip exact)
    buf.seek(0)
    cur.copy_expert(f"COPY {stage} ({', '.join(cols)}) FROM STDIN WITH (FORMAT csv)", buf)

    key_match = " AND ".join(f"s.{k} = t.{k}" for k in keys)
    cur.execute(f"""DELETE FROM {table} t WHERE {scope_sql}
                    AND NOT EXISTS (SELECT 1 FROM {stage} s WHERE {key_match})""", scope_params)
    deleted = cur.rowcount

    cur.execute(f"""
        INSERT INTO {table} AS t ({', '.join(cols)})
        SELECT {', '.join(cols)} FROM {stage}
        ON CONFLICT ({', '.join(keys)}) DO UPDATE
            SET {', '.join(f'{c} = EXCLUDED.{c}' for c in values)}
            WHERE ({', '.join(f't.{c}' for c in values)}) IS DISTINCT FROM ({', '.join(f'EXCLUDED.{c}' for c in values)})
        RETURNING (xmax = 0) AS inserted""")
    flags = [r[0] for r in cur.fetchall()]
    return {"table": table, "inserted": sum(flags), "updated": len(flags) - sum(flags), "deleted": deleted}

In [6]:
def to_multipolygon_ewkb(geoms) -> list[str]:
    """Hex EWKB with SRID 4326, every geometry promoted to MultiPolygon (the column type)."""
    geoms = [shapely.MultiPolygon([g]) if g.geom_type == "Polygon" else g for g in geoms]
    return list(shapely.to_wkb(shapely.set_srid(geoms, 4326), hex=True, include_srid=True))


def load_release(release_dir: Path) -> pd.DataFrame:
    county_xlsx = release_dir / "hpi_at_county.xlsx"
    release_date = part1.read_release_date(county_xlsx)
    hpi = part1.read_fhfa_county(county_xlsx)
    layer, latest = part2.build_layer(release_dir)

    releases = pd.DataFrame({"release_date": [release_date], "latest_year": [latest]})
    hpi_rows = hpi.assign(release_date=release_date)[["release_date", "fips", "year", "hpi"]]
    geom_rows = pd.DataFrame({"geoid": layer.geoid, "name": layer.name, "state": layer.state,
                              "geom": to_multipolygon_ewkb(layer.geometry.values)})
    value_cols = ["geoid", "hpi_yoy_pct", "hpi_cagr_5y_pct", "status", "yoy_source", "cagr_source", "coverage"]
    layer_rows = layer[value_cols].assign(release_date=release_date)[["release_date"] + value_cols]

    scope = ("release_date = %s", (release_date,))
    with conn, conn.cursor() as cur:   # one transaction: all or nothing
        report = [
            sync_table(cur, "releases", releases, ["release_date"], *scope),
            sync_table(cur, "county_geom", geom_rows, ["geoid"]),
            sync_table(cur, "fhfa_county_hpi", hpi_rows, ["release_date", "fips", "year"], *scope),
            sync_table(cur, "layer_values", layer_rows, ["release_date", "geoid"], *scope),
        ]
    return pd.DataFrame(report).assign(release=str(release_date)).set_index(["release", "table"])

## Step 5: Load both releases, then load one again

In [7]:
first_loads = pd.concat([load_release(r) for r in RELEASES])
first_loads

FHFA counties with no 2024 boundary (not on the map): ['09001', '09003', '09005', '09007', '09009', '09011', '09013', '09015']
C:\Projects\data-eng-assessment-055\data\fhfa (released 2025-03-25): latest year 2024, 3144 counties

                        Part 1  Part 2
status
estimated_ct_crosswalk       0       9
estimated_zip                0      37
no_latest                  154     142
no_prior_years               4       4
not_in_fhfa                365     334
partial_no_cagr              2       2
partial_no_yoy              76      73
published                 2543    2543

C:\Projects\data-eng-assessment-055\data\fhfa\next_release (released 2026-03-31): latest year 2025, 3144 counties

                 Part 1  Part 2
status
estimated_zip         0      31
no_latest           118     110
no_prior_years        2       2
not_in_fhfa         349     330
partial_no_cagr       1       1
partial_no_yoy       63      59
published          2611    2611

                            inserted  updated  deleted
release    table
2025-03-25 releases                1        0        0
           county_geom          3144        0        0
           fhfa_county_hpi    103294        0        0
           layer_values         3144        0        0
2026-03-31 releases                1        0        0
           county_geom             0        0        0
           fhfa_county_hpi    106252        0        0
           layer_values         3144        0        0

In [8]:
def fingerprint() -> pd.DataFrame:
    """Row count and an md5 of each table's full contents, to compare before and after."""
    out = []
    for table, order in [("releases", "release_date"), ("county_geom", "geoid"),
                         ("fhfa_county_hpi", "release_date, fips, year"), ("layer_values", "release_date, geoid")]:
        out.append(q(f"SELECT '{table}' AS table, count(*) AS rows, "
                     f"md5(string_agg(t::text, '|' ORDER BY {order})) AS md5 FROM {table} t"))
    return pd.concat(out).set_index("table")


before = fingerprint()
again = load_release(RELEASES[1])
after = fingerprint()
display(again)
print("tables identical after re-loading:", before.equals(after))
before

C:\Projects\data-eng-assessment-055\data\fhfa\next_release (released 2026-03-31): latest year 2025, 3144 counties

                 Part 1  Part 2
status
estimated_zip         0      31
no_latest           118     110
no_prior_years        2       2
not_in_fhfa         349     330
partial_no_cagr       1       1
partial_no_yoy       63      59
published          2611    2611

                            inserted  updated  deleted
release    table
2026-03-31 releases                0        0        0
           county_geom             0        0        0
           fhfa_county_hpi         0        0        0
           layer_values            0        0        0

tables identical after re-loading: True

                   rows                               md5
table
releases              2  4dc090f58ea9f35f17254ff806b6e12f
county_geom        3144  2cd18ddc81aa2081198139f732552279
fhfa_county_hpi  209546  821ad13582b62ed740e09cb1c5989dc7
layer_values       6288  ece9d322d291ff1bca2b4d56567bb329

The second load **inserted, updated and deleted 0 rows**, and the content fingerprints are identical. Loading the releases in the other order (next first, then old) gives the same tables, because each release only touches its own rows.

## Step 6: Querying history

Three dates: before any release, between the two, and after the newest.

In [9]:
dates = ["2025-01-01", "2025-12-01", "2026-06-01"]
pd.concat([q("""SELECT %s::date AS as_of, release_as_of(%s) AS release_used,
                       (SELECT count(*) FROM hpi_as_of(%s)) AS hpi_rows,
                       (SELECT count(*) FROM layer_as_of(%s)) AS layer_rows""", (d, d, d, d)) for d in dates])

        as_of release_used  hpi_rows  layer_rows
0  2025-01-01         None         0           0
0  2025-12-01   2025-03-25    103294        3144
0  2026-06-01   2026-03-31    106252        3144

In [10]:
# Autauga County, AL, as published in each release
pd.concat([q("SELECT %s::date AS as_of, * FROM hpi_as_of(%s) WHERE fips = '01001' AND year >= 2019 ORDER BY year",
             (d, d)) for d in dates[1:]]).pivot(index="year", columns="as_of", values="hpi")

as_of  2025-12-01  2026-06-01
year
2019       191.19      192.89
2020       192.30      193.66
2021       207.76      209.09
2022       236.89      239.86
2023       259.05      262.51
2024       280.30      280.45
2025          NaN      285.46

In [11]:
q("""
SELECT a.status,
       count(*) FILTER (WHERE a.as_of = '2025-12-01') AS "as of 2025-12-01",
       count(*) FILTER (WHERE a.as_of = '2026-06-01') AS "as of 2026-06-01"
FROM (SELECT '2025-12-01'::date AS as_of, status FROM layer_as_of('2025-12-01')
      UNION ALL
      SELECT '2026-06-01'::date, status FROM layer_as_of('2026-06-01')) a
GROUP BY a.status ORDER BY 3 DESC
""")

                   status  as of 2025-12-01  as of 2026-06-01
0               published              2543              2611
1             not_in_fhfa               334               330
2               no_latest               142               110
3          partial_no_yoy                73                59
4           estimated_zip                37                31
5          no_prior_years                 4                 2
6         partial_no_cagr                 2                 1
7  estimated_ct_crosswalk                 9                 0

In [12]:
# The map for one date, straight from the database (geometry included)
import warnings
import geopandas as gpd
with warnings.catch_warnings():   # pandas prefers SQLAlchemy; a plain psycopg2 connection works fine here
    warnings.simplefilter("ignore", UserWarning)
    snap = gpd.read_postgis("SELECT * FROM layer_as_of('2025-12-01')", conn, geom_col="geom")
conn.rollback()
print(snap.shape, snap.crs)
snap.drop(columns="geom").query("state == 'CT'").round(2)

(3144, 12) EPSG:4326

     geoid                                            name state                  status  hpi_yoy_pct  hpi_cagr_5y_pct    yoy_source   cagr_source  coverage release_date  latest_year
341  09110                         Capitol Planning Region    CT  estimated_ct_crosswalk         9.89             9.49  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
343  09120              Greater Bridgeport Planning Region    CT  estimated_ct_crosswalk         7.32             8.97  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
344  09160                 Northwest Hills Planning Region    CT  estimated_ct_crosswalk         7.52            10.05  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
345  09170       South Central Connecticut Planning Region    CT  estimated_ct_crosswalk         7.84             9.64  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
347  09130  Lower Connecticut River Valley Planning Region    CT  estimated_ct_crosswalk         8.52             9.42  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
349  09140                Naugatuck Valley Planning Region    CT  estimated_ct_crosswalk         8.01             9.63  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
350  09150        Northeastern Connecticut Planning Region    CT  estimated_ct_crosswalk         9.12             9.73  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
352  09180        Southeastern Connecticut Planning Region    CT  estimated_ct_crosswalk         7.13             9.77  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024
353  09190             Western Connecticut Planning Region    CT  estimated_ct_crosswalk         7.32             9.03  ct_crosswalk  ct_crosswalk       1.0   2025-03-25         2024

## Step 7: Revisions between the two most recent releases

**`hpi_revisions`** pairs every `(fips, year)` across the two most recent releases and keeps the ones that differ:

| `revision` | Meaning |
|---|---|
| `revised` | a value in both releases, and it changed |
| `added` | blank or absent before, a value now (e.g. a new county code, or a year FHFA now publishes) |
| `removed` | a value before, blank or absent now (e.g. CT's old county codes) |

Because nearly every value changes (FHFA re-estimates everything, and some series were rebased to a new first year), the view also has `pct_change`. `rebased` flags series whose first recorded year moved: their whole level shifts, so `pct_change` there reflects the new base, not new information.

**`status_changes`** compares our layer between the same two releases, for every county whose status differs.

In [13]:
REVISIONS_SQL = """
CREATE OR REPLACE VIEW latest_two_releases AS
SELECT max(release_date) FILTER (WHERE rn = 1) AS new_release,
       max(release_date) FILTER (WHERE rn = 2) AS old_release
FROM (SELECT release_date, row_number() OVER (ORDER BY release_date DESC) AS rn FROM releases) r;

CREATE OR REPLACE VIEW hpi_revisions AS
WITH r AS (SELECT * FROM latest_two_releases),
o AS (SELECT h.fips, h.year, h.hpi FROM fhfa_county_hpi h, r WHERE h.release_date = r.old_release),
n AS (SELECT h.fips, h.year, h.hpi FROM fhfa_county_hpi h, r WHERE h.release_date = r.new_release),
first_year AS (
    SELECT fips,
           min(year) FILTER (WHERE release_date = r.old_release AND hpi IS NOT NULL) AS old_first,
           min(year) FILTER (WHERE release_date = r.new_release AND hpi IS NOT NULL) AS new_first
    FROM fhfa_county_hpi, r GROUP BY fips
)
SELECT coalesce(o.fips, n.fips) AS fips,
       coalesce(o.year, n.year) AS year,
       o.hpi AS old_hpi,
       n.hpi AS new_hpi,
       CASE WHEN o.hpi IS NOT NULL AND n.hpi IS NOT NULL THEN 'revised'
            WHEN o.hpi IS NULL THEN 'added'
            ELSE 'removed' END AS revision,
       round(((n.hpi / nullif(o.hpi, 0) - 1) * 100)::numeric, 4) AS pct_change,
       coalesce(f.old_first IS DISTINCT FROM f.new_first AND f.old_first IS NOT NULL AND f.new_first IS NOT NULL,
                false) AS rebased,
       r.old_release, r.new_release
FROM o FULL JOIN n ON o.fips = n.fips AND o.year = n.year
CROSS JOIN r
LEFT JOIN first_year f ON f.fips = coalesce(o.fips, n.fips)
WHERE r.old_release IS NOT NULL
  AND o.hpi IS DISTINCT FROM n.hpi;

CREATE OR REPLACE VIEW status_changes AS
WITH r AS (SELECT * FROM latest_two_releases),
o AS (SELECT v.* FROM layer_values v, r WHERE v.release_date = r.old_release),
n AS (SELECT v.* FROM layer_values v, r WHERE v.release_date = r.new_release)
SELECT coalesce(o.geoid, n.geoid) AS geoid,
       g.name, g.state,
       o.status AS old_status,
       n.status AS new_status,
       o.hpi_yoy_pct AS old_hpi_yoy_pct, n.hpi_yoy_pct AS new_hpi_yoy_pct,
       r.old_release, r.new_release
FROM o FULL JOIN n ON o.geoid = n.geoid
CROSS JOIN r
LEFT JOIN county_geom g ON g.geoid = coalesce(o.geoid, n.geoid)
WHERE r.old_release IS NOT NULL
  AND o.status IS DISTINCT FROM n.status;
"""

with conn, conn.cursor() as cur:
    cur.execute(REVISIONS_SQL)
q("SELECT * FROM latest_two_releases")

  new_release old_release
0  2026-03-31  2025-03-25

`added` includes the whole new year (2025 exists only in the next release), new county codes (CT regions and a few others), and years FHFA now publishes for the first time. `removed` is mostly CT's old county codes plus values FHFA has since blanked.

In [14]:
q("""SELECT revision, rebased, count(*) AS rows, count(DISTINCT fips) AS counties,
            round(percentile_cont(0.5) WITHIN GROUP (ORDER BY abs(pct_change))::numeric, 2) AS median_abs_pct
     FROM hpi_revisions GROUP BY 1, 2 ORDER BY 1, 2""")

  revision  rebased   rows  counties median_abs_pct
0    added    False   3185      2570           None
1    added     True    318       136           None
2  removed    False    433        21           None
3  removed     True    154        56           None
4  revised    False  94275      2638           0.44
5  revised     True   4397       139           8.21

In [15]:
# Revisions to recent years: how much did the picture of 2020-2024 change?
q("""SELECT year, count(*) AS revised,
            round(avg(pct_change), 2) AS mean_pct, round(avg(abs(pct_change)), 2) AS mean_abs_pct
     FROM hpi_revisions WHERE revision = 'revised' AND NOT rebased AND year >= 2020
     GROUP BY year ORDER BY year""")

   year  revised mean_pct mean_abs_pct
0  2020     2623     0.14         1.07
1  2021     2633     0.20         1.11
2  2022     2596     0.18         1.27
3  2023     2483     0.18         1.55
4  2024     2493     0.12         1.52

In [16]:
q("SELECT * FROM hpi_revisions WHERE fips LIKE '09%%' ORDER BY fips, year DESC LIMIT 6")

    fips  year  old_hpi new_hpi revision pct_change  rebased old_release new_release
0  09001  2024  1057.67    None  removed       None    False  2025-03-25  2026-03-31
1  09001  2023   985.54    None  removed       None    False  2025-03-25  2026-03-31
2  09001  2022   898.83    None  removed       None    False  2025-03-25  2026-03-31
3  09001  2021   786.59    None  removed       None    False  2025-03-25  2026-03-31
4  09001  2020   704.45    None  removed       None    False  2025-03-25  2026-03-31
5  09001  2019   688.21    None  removed       None    False  2025-03-25  2026-03-31

In [17]:
q("""SELECT coalesce(old_status, '(none)') AS old_status, coalesce(new_status, '(none)') AS new_status,
            count(*) AS counties
     FROM status_changes GROUP BY 1, 2 ORDER BY 3 DESC""")

                old_status       new_status  counties
0                no_latest   partial_no_yoy        58
1           partial_no_yoy        published        50
2           partial_no_yoy        no_latest        23
3                published        no_latest        20
4                no_latest        published        19
5   estimated_ct_crosswalk        published         9
6              not_in_fhfa        no_latest         5
7            estimated_zip        published         5
8            estimated_zip      not_in_fhfa         3
9           no_prior_years        published         3
10               no_latest   no_prior_years         2
11               no_latest      not_in_fhfa         2
12             not_in_fhfa        published         2
13          no_prior_years        no_latest         1
14             not_in_fhfa   partial_no_yoy         1
15               no_latest    estimated_zip         1
16               published  partial_no_cagr         1
17         partial_no_cagr        published         1
18         partial_no_cagr        no_latest         1
19             not_in_fhfa    estimated_zip         1

In [18]:
q("SELECT geoid, name, state, old_status, new_status FROM status_changes WHERE state = 'CT' ORDER BY geoid")

   geoid                                            name state              old_status new_status
0  09110                         Capitol Planning Region    CT  estimated_ct_crosswalk  published
1  09120              Greater Bridgeport Planning Region    CT  estimated_ct_crosswalk  published
2  09130  Lower Connecticut River Valley Planning Region    CT  estimated_ct_crosswalk  published
3  09140                Naugatuck Valley Planning Region    CT  estimated_ct_crosswalk  published
4  09150        Northeastern Connecticut Planning Region    CT  estimated_ct_crosswalk  published
5  09160                 Northwest Hills Planning Region    CT  estimated_ct_crosswalk  published
6  09170       South Central Connecticut Planning Region    CT  estimated_ct_crosswalk  published
7  09180        Southeastern Connecticut Planning Region    CT  estimated_ct_crosswalk  published
8  09190             Western Connecticut Planning Region    CT  estimated_ct_crosswalk  published

## Step 8: Check the README contract

The minimum columns each object must return.

In [19]:
required = {
    "hpi_as_of('2026-06-01')": {"fips", "year", "hpi"},
    "layer_as_of('2026-06-01')": {"geoid", "status", "hpi_yoy_pct", "hpi_cagr_5y_pct"},
    "hpi_revisions": {"fips", "year", "old_hpi", "new_hpi"},
    "status_changes": {"geoid", "old_status", "new_status"},
}
for obj, cols in required.items():
    got = set(q(f"SELECT * FROM {obj} LIMIT 0").columns)
    print(f"{obj:28s} {'OK' if cols <= got else 'MISSING ' + str(cols - got)}")

hpi_as_of('2026-06-01')      OK
layer_as_of('2026-06-01')    OK
hpi_revisions                OK
status_changes               OK

In [20]:
conn.close()

## Decisions to carry into `NOTES.md`

- **Releases are keyed by FHFA's publication date** ("Last updated"), so `as of d` means "what FHFA had published by d", independent of when we loaded it.
- **FHFA values are stored exactly as published**, blanks and old CT codes included; the layer is stored separately per release.
- **Idempotent load**: stage → delete missing → upsert only rows that differ, in one transaction. A repeat load touches 0 rows (Step 5).
- **Shapes stored once** (both releases use the 2024 boundaries); `layer_as_of` joins them back.
- **Revisions**: `revised` / `added` / `removed`, with `pct_change` and a `rebased` flag, because nearly every value changes between releases and rebased series shift their whole level.